name: auto deploy
on:
  push:
    branches:
      - master
  release:
    types:
    - published

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: 检查分支
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Autotagger
        uses: ButlerLogic/action-autotag@1.1.1
        with:
          GITHUB_TOKEN: "${{ secrets.TOKEN }}"
          strategy: package
          root: "/"
          tag_prefix: "v"
          commit_message_template: "({{sha}} by {{author}}) {{message}}"
          version: "${{ steps.previous_step.outputs.version }}"

      - name: Create .env file
        env: 
          MYSQL_PWD: ${{ secrets.MYSQL_PWD }}
        run: |
          touch .env
          echo MYSQL_USERNAME =${{ secrets.MYSQL_USERNAME }} >> .env
          echo MYSQL_PWD ="$(base64 -d <<< "$MYSQL_PWD")" >> .env
          echo MYSQL_DATABASE =${{ secrets.MYSQL_DATABASE }} >> .env
          echo MYSQL_HOST =${{ secrets.MYSQL_HOST }} >> .env
          echo MYSQL_PORT =${{ secrets.MYSQL_PORT }} >> .env

      - name: 安装 Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"


      - name: 安装依赖
        run: |
          npm install --save

      - name: 构建
        run: |
          npm run build --if-present

      - name: 部署启动
        run: |
          pm2 restart baby-shop-server
